[workspace]

members = [
    "Day1", "Day10", "Day10-2", "Day11", "Day12", "Day13", "Day14", "Day15", "Day2", "Day3", 
    "Day4", "Day5", "Day6", "Day7", "Day7-2", "Day8", "Day8-2", "Day9", "Day9-2",
]
